baseURL = "https://grapefruitmoon.net/"
theme = "risotto"
title = "Grapefruitmoon.net"
author = "Alan Wood"
copyright = "© Alan Wood"
languageCode = "en"
DefaultContentLanguage = "en"

enableInlineShortcodes = true
canonifyurls = true

[pagination]
pagerSize = 10

[params]
noindex = false

[params.theme]
palette = "gruvbox-dark"

# Sidebar: about/bio
[params.about]
title = "Grapefruitmoon.net"
description = "Data nerd, musician, herbivore. Where I might talk about data, tech, music, sports and other related nonsense."
logo = "🍊"

# Sidebar: social links
[[params.socialLinks]]
icon = "fa-brands fa-twitter"
title = "Twitter"
url = "https://twitter.com/grapefruitmoon/"

[taxonomies]
category = "categories"
tag = "tags"

# For inline HTML in posts
[markup.goldmark.renderer]
unsafe = true

[markup]
# Syntax highlighting
[markup.highlight]
style = "monokai"

# Table of contents
[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2